Using path block:
± |path_block ✗| → bundle
Resolving dependencies...
Using rake 10.4.2
Using i18n 0.7.0
Using json 1.8.2
Using minitest 5.6.1
Using thread_safe 0.3.5
Using tzinfo 1.2.2
Using activesupport 4.1.9
Using builder 3.2.2
Using erubis 2.7.0
Using actionview 4.1.9
Using rack 1.5.3
Using rack-test 0.6.3
Using actionpack 4.1.9
Using mime-types 2.5
Using mail 2.6.3
Using actionmailer 4.1.9
Using activemodel 4.1.9
Using arel 5.0.1.20140414130214
Using activerecord 4.1.9
Using bundler 1.9.5
Using thor 0.19.1
Using railties 4.1.9
Using hike 1.2.3
Using multi_json 1.11.0
Using tilt 1.4.1
Using sprockets 2.12.3
Using sprockets-rails 2.3.0
Using rails 4.1.9
Using b 0.0.1 from source at components
Using a 0.0.1 from source at components
Using coffee-script-source 1.9.1.1
Using execjs 2.5.2
Using coffee-script 2.4.1
Using coffee-rails 4.0.1
Using jbuilder 2.2.13
Using jquery-rails 3.1.2
Using rdoc 4.2.0
Using sass 3.2.19
Using sass-rails 4.0.5
Using sdoc 0.4.1
Using spring 1.3.5
Using sqlite3 1.3.10
Using turbolinks 2.5.3
Using uglifier 2.7.1
Bundle complete! 11 Gemfile dependencies, 44 gems now installed.
Use `bundle show [gemname]` to see where a bundled gem is installed.



± |path_block ✗| → rails c
Loading development environment (Rails 4.1.9)
2.2.1 :001 > A
 => A
2.2.1 :002 > B
 => B
2.2.1 :003 > Azzer
 => Azzer
2.2.1 :004 > Buzzer
NameError: uninitialized constant Buzzer
	from (irb):4
	from /Users/stephan/.rvm/gems/ruby-2.2.1/gems/railties-4.1.9/lib/rails/commands/console.rb:90:in `start'
	from /Users/stephan/.rvm/gems/ruby-2.2.1/gems/railties-4.1.9/lib/rails/commands/console.rb:9:in `start'
	from /Users/stephan/.rvm/gems/ruby-2.2.1/gems/railties-4.1.9/lib/rails/commands/commands_tasks.rb:69:in `console'
	from /Users/stephan/.rvm/gems/ruby-2.2.1/gems/railties-4.1.9/lib/rails/commands/commands_tasks.rb:40:in `run_command!'
	from /Users/stephan/.rvm/gems/ruby-2.2.1/gems/railties-4.1.9/lib/rails/commands.rb:17:in `<top (required)>'
	from /Users/stephan/workspace/cbra/path_block_sample/bin/rails:8:in `<top (required)>'
	from /Users/stephan/.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /Users/stephan/.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from -e:1:in `<main>'